name: workflow runners

on: push

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: show os
              run: |
                echo "running on ubuntu runner"
                echo "Runner OS : $RUNNER_OS"

    windows-os:
        runs-on: windows-latest
        steps:
            - name: show os 
              shell: bash
              run : |
                echo "running on ubuntu runner"
                echo "Runner OS : $RUNNER_OS"